version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of Python package manifests (e.g., requirements.txt or pyproject.toml)
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "deps" # Customize commit message prefix for Python updates
    open-pull-requests-limit: 10 # Limit the number of open PRs to avoid overload
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "deps" # Customize commit message prefix for GitHub Actions updates
    open-pull-requests-limit: 5 # Limit the number of open PRs for GitHub Actions
    labels:
      - "github-actions"
