info: {}
name: seal_ring_gdsfactorypco_540c1ebf
settings:
  padding: 10
  seal: via_stack
  size:
  - 500
  - 500
  width: 10
  with_east: true
  with_north: true
  with_south: true
  with_west: true
