info: {}
name: mmi1x2_gdsfactorypcompo_1f097353
settings:
  cross_section: strip
  gap_mmi: 0.25
  length_mmi: 5.5
  length_taper: 10
  straight: straight
  taper: taper
  width_mmi: 2.5
  width_taper: 1
