info:
  column_pitch: 2
  enclosure: 2
  row_pitch: 2
  xsize: 0.7
  ysize: 0.7
name: via_gdsfactorypcomponen_efa29aa3
settings:
  bbox_offset: 0
  enclosure: 2
  layer: VIA1
  pitch: 2
  size:
  - 0.7
  - 0.7
