info:
  resistance: 0
name: resistance_sheet_gdsfac_cb73a501
settings:
  layer_offsets:
  - 0
  - 0.2
  layers:
  - HEATER
  pad: via_stack_heater_mtop
  pad_pitch: 100
  pad_port_name: e4
  pad_size:
  - 50
  - 50
  width: 10
