info: {}
name: rectangle_with_slits_gd_442d6bfc
settings:
  centered: false
  layer: WG
  layer_slit: SLAB150
  size:
  - 100
  - 200
  slit_column_pitch: 20
  slit_enclosure: 10
  slit_row_pitch: 20
  slit_size:
  - 1
  - 1
