info: {}
name: via_chain_gdsfactorypco_b1f2c27f
settings:
  cols: 10
  contact: via_stack_m2_m3
  contact_offset: 0
  layers_bot:
  - M1
  layers_top:
  - M2
  min_metal_spacing: 1
  num_vias: 100
  offsets_bot:
  - 0
  offsets_top:
  - 0
  via: via1
  via_min_enclosure: 1
