info:
  components: 80
name: cutback_2x2_gdsfactoryp_2b86b30c
settings:
  bend180: bend_circular180
  cols: 4
  component: mmi2x2
  cross_section: strip
  mirror: false
  port1: o1
  port2: o2
  port3: o3
  port4: o4
  rows: 5
  straight: straight
