info:
  dy: 0
  length: 42.817
  min_bend_radius: 9.086
  radius: 10
  route_info_length: 42.817
  route_info_min_bend_radius: 9.086
  route_info_n_bend_90: 2
  route_info_strip_length: 42.817
  route_info_type: strip
  route_info_weight: 42.817
  width: 0.5
name: bend_euler_gdsfactorypc_0bdc9c24
settings:
  allow_min_radius_violation: false
  angle: 180
  cross_section: strip
  p: 0.5
  with_arc_floorplan: true
