info:
  doe_names:
  - mmi1x2_gdsfactorypcompo_e7347a11
  - mmi1x2_gdsfactorypcompo_970bc9eb
  doe_settings:
  - length_mmi: 100
  - length_mmi: 200
name: pack_doe_grid_gdsfactor_2a414c56
settings:
  do_permutations: false
  doe: mmi1x2
  settings:
    length_mmi:
    - 100
    - 200
  with_text: false
