info:
  area: 80
  num_squares: 750
  xsize: 10
  ysize: 8
name: snspd_gdsfactorypcompon_720d3387
settings:
  layer:
  - 1
  - 0
  port_type: electrical
  size:
  - 10
  - 8
  terminals_same_side: false
  turn_ratio: 4
  wire_pitch: 0.6
  wire_width: 0.2
