info: {}
name: pad_array_gdsfactorypco_dc726c53
settings:
  auto_rename_ports: false
  centered_ports: false
  column_pitch: 150
  columns: 1
  layer: MTOP
  pad: pad
  port_orientation: 180
  row_pitch: 150
  rows: 3
