info: {}
name: cdsem_bend180_gdsfactor_16eb1146
settings:
  bend90: bend_circular
  cross_section: strip
  radius: 10
  straight: straight
  text: text_rectangular
  text_size: 1
  wg_length: 420
  width: 0.5
