info: {}
name: pad_array_gdsfactorypco_c1dae302
settings:
  auto_rename_ports: false
  centered_ports: false
  column_pitch: 150
  columns: 6
  layer: MTOP
  pad: pad
  port_orientation: 90
  row_pitch: 150
  rows: 1
