info:
  length: 20
name: taper_sc_nc_gdsfactoryp_5bac8726
settings:
  cross_section: strip
  layer_nitride: WGN
  layer_wg: WG
  length: 20
  width1: 0.5
  width2: 1
  width_tip_nitride: 0.15
  width_tip_silicon: 0.15
