info:
  length: 20
name: taper_nc_sc_gdsfactoryp_e4a7bb2c
settings:
  cross_section: strip
  layer_nitride: WGN
  layer_wg: WG
  length: 20
  width1: 1
  width2: 0.5
  width_tip_nitride: 0.15
  width_tip_silicon: 0.15
