info: {}
name: straight_pin_slot_gdsfa_779980e0
settings:
  cross_section: pin
  length: 500
  taper: taper_strip_to_ridge
  via_stack: via_stack_m1_mtop
  via_stack_slab: via_stack_slab_m1_horizontal
  via_stack_slab_spacing: 2
  via_stack_spacing: 3
  via_stack_width: 10
