info: {}
name: disk_heater_gdsfactoryp_9f50c453
settings:
  cross_section: strip
  gap: 0.2
  heater_extent: 2
  heater_layer: HEATER
  heater_width: 5
  parity: 1
  port_orientation: 90
  radius: 10
  via_stack: via_stack_heater_mtop
  via_width: 10
  wrap_angle_deg: 180
