info: {}
name: compass_gdsfactorypcomp_f0e3e03f
settings:
  auto_rename_ports: true
  layer: WG
  port_inclusion: 0
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: electrical
  size:
  - 4
  - 2
