info: {}
name: mode_converter_gdsfacto_10a30c65
settings:
  bend: Fbend_s_Mgdsfactorypcomponentspbendspbend_s_SS25_3
  coupler_straight_asymmetric: coupler_straight_asymmetric
  cross_section: strip
  gap: 0.3
  length: 10
  mc_mm_width: 1
  mm_width: 1.2
  sm_width: 0.5
  taper: taper
  taper_length: 25
