info: {}
name: grating_coupler_tree_gd_ef3cc62e
settings:
  bend: bend_euler
  cross_section: strip
  fanout_length: 0
  grating_coupler: grating_coupler_elliptical_te
  n: 4
  straight_spacing: 4
  with_loopback: false
