info:
  length: 10
  size:
  - 10
  - 10
name: via_corner_gdsfactorypc_aeaeec6c
settings:
  cross_section:
  - - metal2
    - - 0
      - 180
  - - metal3
    - - 90
      - 270
  layers_labels:
  - m2
  - m3
  vias:
  - via1
