info: {}
name: coupler_broadband_gdsfa_ee79a992
settings:
  bend: bend_euler
  coupler_straight: coupler_straight
  cross_section: strip
  gap_pc: 0.3
  gap_sc: 0.2
  legnth_taper: 1
  lenght_coupler_big_gap: 4.7
  length_coupler_straight: 12.4
  radius: 10
  w_sc: 0.5
  w_top: 0.6
