info: {}
name: spiral_racetrack_heater_fbc193ed
settings:
  bend: bend_euler
  bend_s: bend_s
  heater_cross_section: npp
  num: 8
  spacing: 2
  straight: straight
  straight_length: 30
  waveguide_cross_section: strip
