info: {}
name: cdsem_straight_density__28757169
settings:
  cross_section: strip_no_ports
  gaps:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  label: ''
  length: 420
  text: text_rectangular
  text_size: 1
  widths:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
