info:
  polarization: te
  wavelength: 1.554
name: grating_coupler_ellipti_98bf2b47
settings:
  bias_gap: 0
  cross_section: strip
  fiber_angle: 15
  gaps:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  layer_slab: SLAB150
  nclad: 1.443
  polarization: te
  spiked: true
  taper_angle: 60
  taper_length: 16.6
  taper_to_slab_offset: -3
  wavelength: 1.554
  widths:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
