info:
  column_pitch: 2
  enclosure: 1
  row_pitch: 2
  xsize: 0.7
  ysize: 0.7
name: via_gdsfactorypcomponen_c51b5ebb
settings:
  bbox_offset: 0
  enclosure: 1
  layer: VIA2
  pitch: 2
  size:
  - 0.7
  - 0.7
