info: {}
name: spiral_racetrack_heater_4edb23b1
settings:
  bend: bend_euler
  bend_s: bend_s
  heater_cross_section: heater_metal
  num: 8
  spacing: 2
  straight: straight
  straight_length: 30
  via_stack: via_stack_heater_mtop
  waveguide_cross_section: strip
