info:
  size:
  - 80
  - 80
  xsize: 80
  ysize: 80
name: pad_gdsfactorypcomponen_ea0497a0
settings:
  layer: MTOP
  port_inclusion: 0
  port_orientation: 0
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: pad
  size:
  - 80
  - 80
