info: {}
name: mzi_gdsfactorypcomponen_92da31c1
settings:
  add_optical_ports_arms: false
  auto_rename_ports: true
  bend: bend_euler
  combiner: mmi2x2
  cross_section: strip
  delta_length: 10
  length_x: 200
  length_y: 2
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  port1: o1
  port2: o2
  port_e0_combiner: o4
  port_e0_splitter: o4
  port_e1_combiner: o3
  port_e1_splitter: o3
  splitter: mmi2x2
  straight: straight
  straight_x_top: straight_heater_metal
  with_splitter: true
