info: {}
name: ring_crow_couplers_gdsf_cb10ddba
settings:
  bends:
  - bend_circular
  - bend_circular
  - bend_circular
  couplers:
  - coupler
  - coupler
  - coupler
  - coupler
  radius:
  - 10
  - 10
  - 10
  ring_cross_sections:
  - strip
  - strip
  - strip
