info:
  length: 10
name: taper_strip_to_ridge_gd_7e0e0eeb
settings:
  cross_section: strip
  layer_slab: SLAB150
  layer_wg: WG
  length: 10
  use_slab_port: false
  w_slab1: 0.15
  w_slab2: 6
  width1: 0.5
  width2: 0.5
