info:
  length: 10
  width1: 0.5
  width2: 0.5
name: taper_gdsfactorypcompon_b49e6ea0
settings:
  cross_section: metal_routing
  length: 10
  port_names:
  - e1
  - e2
  port_types:
  - electrical
  - electrical
  width1: 0.5
  with_bbox: true
  with_two_ports: true
