# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: "GDSFactory"
author: GDSFactory
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: false
  # timeout: -1
  # execute_notebooks: force
  # execute_notebooks: "off"
  exclude_patterns:
    - "*01_pin_waveguide*"
    - "*1_fdtd_sparameters*"
    - "*2_interconnect*"
    - "*ray_optimiser*"
    - "*03_numerical_implantation*"
    - "*02_model_extraction*"
    # - "*20_schematic_driven_layout*"
    # - "*001_meep_sparameters*"
    # - "*00_tidy3d.ipynb"
    # - "*03_cascaded_mzi*"
    # - "*jupyter_notebooks*"
latex:
  latex_engine: pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use sphinx-jupyterbook-latex for pdf builds as default
# Add a bibtex file so that we can create citations
html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://gdsfactory.github.io/gdsfactory/
  theme:
  name: "sphinx_book_theme"
  options:
    logo:
      light: "_static/logo_black.png"
      dark: "_static/logo_white.png"
# Information about where the book exists on the web
repository:
  url: https://github.com/gdsfactory/gdsfactory # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)
# launch_buttons:
# binderhub_url: "https://mybinder.org/v2/gh/gdsfactory/binder-sandbox/HEAD"
# thebe: true
# jupyterhub_url: "https://mybinder.org/v2/gh/gdsfactory/binder-sandbox/HEAD"
# notebook_interface: jupyterlab
# colab_url: "https://colab.research.google.com"
sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.autodoc.typehints"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
    - "matplotlib.sphinxext.plot_directive"
    # - "sphinxcontrib.autodoc_pydantic"
  config:
    #autodoc_typehints: description
    autodoc_type_aliases:
      "ComponentFactory": "ComponentFactory"
      "ComponentSpec": "ComponentSpec"
      "CrossSectionFactory": "CrossSectionFactory"
      "CrossSectionSpec": "CrossSectionSpec"
      "LayerSpec": "LayerSpec"
      "LayerSpecs": "LayerSpecs"
      "Layer": "Layer"
      "Layers": "Layers"
      "PathType": "PathType"
    nb_execution_show_tb: True
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    nb_execution_raise_on_error: true
    # nb_custom_formats:
    #     .py:
    #         - jupytext.reads
    #         - fmt: py
    html_theme_options:
      logo:
        image_light: logo_white.png
        image_dark: logo_black.png
